backend:
  name: git-gateway
  branch: main
collections:
  - name: "recipes"
    label: "Recipes"
    folder: "recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Servings", name: "servings", widget: "number", default: 2 }
      - { label: "Ingredients", name: "ingredients", widget: "list", fields: [{label: "Quantity", name: "quantity", widget: "number"}, {label: "Unit", name: "unit", widget: "string"}, {label: "Item", name: "item", widget: "string"}] }
      - { label: "Instructions", name: "body", widget: "markdown" }

